version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    build:
      dockerfile: ./build/Dockerfile
      context: ..
