version: '3.9'
services:
  mysql:
    ports:
      - "3306:3306"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "highload"
      MYSQL_USER: "db"
      MYSQL_PASSWORD: "db"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - internal
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - internal
  app:
    depends_on:
      - mysql
      - redis
    ports:
      - "80:80"
    build:
      dockerfile: ./build/Dockerfile
      context: ..
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28