version: '3'
services:
  mysql:
    ports:
      - "3306:3306"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "highload"
      MYSQL_USER: "db"
      MYSQL_PASSWORD: "db"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    build:
      dockerfile: ./build/Dockerfile
      context: ..
